# Generated by Django 5.0.6 on 2024-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ST', 'Successful transaction'), ('FT', 'Transaction failed'), ('II', 'Insufficient inventory'), ('RJ', 'Rejected')], default='RJ', max_length=2),
        ),
    ]
