# Generated by Django 5.0.6 on 2024-07-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_gateway', '0002_transaction_status_alter_account_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='transaction_status',
        ),
    ]
